version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - npm_config_unsafe_perm=true
